services:
  php:
    build:
      context: ./.docker/php
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: launchlab
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
